<?php
namespace Application\lib;

class Error {
    // etc.
    public static $REQUIRED_PARAM = 'REQUIRED_PARAM';
    public static $ALLOW_EXTENSION = 'ALLOW_EXTENSION';
    public static $UPLOAD_FAILED = 'UPLOAD_FAILED';
    public static $MAIL_SEND = 'MAIL_SEND';
    // Account
    public static $VALIDATION_USER_ID = 'VALIDATION_USER_ID';
    public static $VALIDATION_USER_NAME = 'VALIDATION_USER_NAME';
    public static $VALIDATION_EMAIL = 'VALIDATION_EMAIL';
    public static $VALIDATION_PASSWORD = 'VALIDATION_PASSWORD';
    public static $VALIDATION_OLD_PASSWORD = 'VALIDATION_OLD_PASSWORD';
    public static $VALIDATION_NEW_PASSWORD = 'VALIDATION_NEW_PASSWORD';
    public static $VERIFY_PASSWORD_FAILED = 'VERIFY_PASSWORD_FAILED';
    public static $VALIDATION_BIRTHDAY = 'VALIDATION_BIRTHDAY';
    public static $VALIDATION_GENDER = 'VALIDATION_GENDER';
    public static $ALREADY_USER_ID = 'ALREADY_USER_ID';
    public static $ALREADY_EMAIL = 'ALREADY_EMAIL';
    public static $UNKNOWN_USER = 'UNKNOWN_USER';
    public static $VALIDATION_LINE_ID = 'VALIDATION_LINE_ID';
    public static $VALIDATION_INTRODUCTION = 'VALIDATION_INTRODUCTION';
    public static $UNKNOWN_TARGET_USER = 'UNKNOWN_TARGET_USER';
    // Token
    public static $UNKNOWN_TOKEN = 'UNKNOWN_TOKEN';
    // Group
    public static $UNKNOWN_GROUP = 'UNKNOWN_GROUP';
    public static $ALREADY_CREATE_GROUP = 'ALREADY_CREATE_GROUP';
    public static $ALREADY_BELONG_GROUP = 'ALREADY_BELONG_GROUP';
    public static $UNREADY_BELONG_GROUP = 'UNREADY_BELONG_GROUP';
    public static $VALIDATION_GROUP_ID = 'VALIDATION_GROUP_ID';
    public static $VALIDATION_GROUP_NAME = 'VALIDATION_GROUP_NAME';
    public static $VALIDATION_PIN_CODE = 'VALIDATION_PIN_CODE';
    public static $VERIFY_PIN_CODE = 'VERIFY_PIN_CODE';
    // Timeline
    public static $NOT_FIND_POST_CONTENT = 'NOT_FIND_POST_CONTENT';
    public static $DUPLICATE_MEDIA_FILE = 'DUPLICATE_MEDIA_FILE';
    public static $VALIDATION_TIMELINE_POST_CONTENT = 'VALIDATION_TIMELINE_POST_CONTENT';
    public static $GENERATE_THUMBNAIL = 'GENERATE_THUMBNAIL';
    public static $UNKNOWN_POST = 'UNKNOWN_POST';
    public static $UNAUTHORIZED_OPERATION = 'UNAUTHORIZED_OPERATION';
    public static $VALIDATION_TIMELINE_POST_COMMENT = 'VALIDATION_TIMELINE_POST_COMMENT';
    public static $UNKNOWN_COMMENT = 'UNKNOWN_COMMENT';
    // Child
    public static $VALIDATION_AGE = 'VALIDATION_AGE';
    public static $VALIDATION_BLOOD_TYPE = 'VALIDATION_BLOOD_TYPE';
    public static $VALIDATION_BODY_HEIGHT = 'VALIDATION_BODY_HEIGHT';
    public static $VALIDATION_BODY_WEIGHT = 'VALIDATION_BODY_WEIGHT';
    public static $VALIDATION_CLOTHES_SIZE = 'VALIDATION_CLOTHES_SIZE';
    public static $VALIDATION_SHOES_SIZE = 'VALIDATION_SHOES_SIZE';
    public static $VALIDATION_VACCINATION = 'VALIDATION_VACCINATION';
    public static $VALIDATION_ALLERGY = 'VALIDATION_ALLERGY';
    public static $UNKNOWN_CHILD = 'UNKNOWN_CHILD';
    public static $VALIDATION_ADD_DATE = 'VALIDATION_ADD_DATE';
    public static $VALIDATION_DIARY_POST_CONTENT = 'VALIDATION_DIARY_POST_CONTENT';
    public static $VALIDATION_DIARY_POST_COMMENT = 'VALIDATION_DIARY_POST_COMMENT';
    public static $ALREADY_RECORD = 'ALREADY_RECORD';
    // Calendar
    public static $VALIDATION_TITLE = 'VALIDATION_TITLE';
    public static $VALIDATION_CONTENT = 'VALIDATION_CONTENT';
    public static $VALIDATION_DATE = 'VALIDATION_DATE';
    public static $VALIDATION_REMIND_FLG = 'VALIDATION_REMIND_FLG';
    public static $VALIDATION_BEGIN_DATE = 'VALIDATION_BEGIN_DATE';
    public static $VALIDATION_END_DATE = 'VALIDATION_END_DATE';
    public static $GENERATE_MODEL_FAILED = 'GENERATE_MODEL_FAILED';
    public static $VALIDATION_FRIEND_MEMO = 'VALIDATION_FRIEND_MEMO';
    public static $UNKNOWN_FRIEND = 'UNKNOWN_FRIEND';
    public static $UNKNOWN_FACE = 'UNKNOWN_FACE';
}